pipeline {
    agent any
    parameters {
    string defaultValue: 'Dada', name: 'LASTNAME'
    }
    environment {
        NAME = 'Shina'
    }
    tools {
        maven 'Maven'
    }
    stages {
        stage('build') {
            steps {
                echo "This is build stage"
                sh 'mvn clean package'
            }
            

                   }
                   
        stage('test') {
            
            parallel {
                stage(TestA){
                     steps {
                        echo "This is test A"
                        echo " My name is $NAME ${params.LASTNAME}"
                     }
                }
                stage(TestB){
                     steps {
                        echo "This is test B"                
                     }
                }
                stage(TestC){
                     steps {
                        echo "This is test stage C"
                     }
                } 
                
                                         
            }  
        }
        stage('deploy') {
            steps {
                echo "This is deploy stage"
            }

        }
    }

}