pipeline {
    agent any
    parameters {
    string defaultValue: 'Dada', name: 'LASTNAME'
    choice choices: ['dev', 'prod'], name: 'select_environment'
    }
    environment {
        NAME = 'Shina'
    }
    tools {
        maven 'Maven'
    }
    stages {
        stage('build') {
            steps {
                echo "This is build stage"
                sh 'mvn clean package -DskipTests=true'
            }
            

                   }

        stage('test') {
            
            parallel {
                stage(TestA){
                     agent any
                     steps {
                        echo "This is test A"
                        echo " My name is $NAME ${params.LASTNAME}"
                        sh "mvn test"
                     }
                }
                stage(TestB){
                     steps {
                        echo "This is test B" 
                        sh "mvn test"               
                     }
                }
                stage(TestC){
                     steps {
                        echo "This is test stage C"
                     }
                } 
                
                                         
            }  
            post {
                success {
                    //archiveArtifact artifacts: "**/target/*.jar"
                    echo "Build was a success"
                }
            }  
        }
        stage('deploy_dev') {
            //when { expression {params.select_enviroment == dev}}
            when {
                environment name: 'select_environment', value: 'dev'
                }
            steps {
                echo "This is deploy dev stage"
            }

        }
        stage('deploy_prod') {
        //when { expression {params.select_enviroment == prod}}
        when {
            environment name: 'select_environment', value: 'prod'
            }
        steps {
            echo "This is deploy prod stage"
        }

    }
    }

}